/*
 *  SPDX-License-Identifier: Apache-2.0
 *
 *  Copyright The original authors
 *
 *  Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
package dev.hardwood.internal.reader;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;

import dev.hardwood.InputFile;
import dev.hardwood.reader.ParquetFileReader;
import dev.hardwood.reader.RowReader;

import static org.assertj.core.api.Assertions.assertThat;

/// Integration test for [MappedInputFile] with files larger than 2 GB.
///
/// Verifies that neither the Java 21 multiple-mapping fallback nor the Java 22
/// [java.lang.foreign.MemorySegment]-based primary path overflows the `int` offset
/// arithmetic that previously limited reads to files smaller than `Integer.MAX_VALUE`
/// bytes.
///
/// The test fixture `large_file_test.parquet` is generated by `simple-datagen.py`
/// and has a single row group with columns laid out so that later column chunks begin
/// beyond the 2 GB boundary. The file is skipped gracefully when absent (e.g. in CI
/// environments that have not run the data-generation step).
///
/// Run the data-generation step with:
/// ```
/// source .docker-venv/bin/activate && python simple-datagen.py
/// ```
class LargeFileMappedInputFileIT {

    /// Row count and sentinel constants that must match `simple-datagen.py`.
    private static final long ROWS         = 75_000_000L;
    private static final long FIRST_ID     = 1_000_000_001L;
    private static final long LAST_ID      = FIRST_ID + ROWS - 1;
    private static final float FIRST_VALUE = 3.14f;
    private static final float LAST_VALUE  = 2.71f;

    private static final Path FIXTURE = Paths.get("src/test/resources/large_file_test.parquet");

    @Test
    void readsFooterAndSchemaFromLargeFile() throws Exception {
        assumeFixturePresent();

        try (ParquetFileReader reader = ParquetFileReader.open(InputFile.of(FIXTURE))) {
            assertThat(reader.getFileMetaData().numRows()).isEqualTo(ROWS);
            assertThat(reader.getFileSchema().getColumnCount()).isEqualTo(3);
            assertThat(reader.getFileSchema().getColumn(0).name()).isEqualTo("id");
            assertThat(reader.getFileSchema().getColumn(1).name()).isEqualTo("value");
            assertThat(reader.getFileSchema().getColumn(2).name()).isEqualTo("marker");
        }
    }

    @Test
    void readsFirstRowFromLargeFile() throws Exception {
        assumeFixturePresent();

        try (ParquetFileReader reader = ParquetFileReader.open(InputFile.of(FIXTURE));
                RowReader rowReader = reader.createRowReader()) {
            assertThat(rowReader.hasNext()).isTrue();
            rowReader.next();
            assertThat(rowReader.getLong("id")).isEqualTo(FIRST_ID);
            assertThat(rowReader.getFloat("value")).isCloseTo(FIRST_VALUE, org.assertj.core.data.Offset.offset(1e-3f));
            assertThat(rowReader.getInt("marker")).isEqualTo(0);
        }
    }

    @Test
    void readsLastRowFromLargeFile() throws Exception {
        assumeFixturePresent();

        try (ParquetFileReader reader = ParquetFileReader.open(InputFile.of(FIXTURE));
                RowReader rowReader = reader.createRowReader()) {
            // Skip to last row
            long target = ROWS - 1;
            long skipped = 0;
            while (skipped < target && rowReader.hasNext()) {
                rowReader.next();
                skipped++;
            }
            assertThat(rowReader.hasNext()).isTrue();
            rowReader.next();
            assertThat(rowReader.getLong("id")).isEqualTo(LAST_ID);
            assertThat(rowReader.getFloat("value")).isCloseTo(LAST_VALUE, org.assertj.core.data.Offset.offset(1e-3f));
            assertThat(rowReader.getInt("marker")).isEqualTo((int) (ROWS - 1));
        }
    }

    @Test
    void rowCountMatchesMetadata() throws Exception {
        assumeFixturePresent();

        try (ParquetFileReader reader = ParquetFileReader.open(InputFile.of(FIXTURE));
                RowReader rowReader = reader.createRowReader()) {
            long count = 0;
            while (rowReader.hasNext()) {
                rowReader.next();
                count++;
            }
            assertThat(count).isEqualTo(ROWS);
        }
    }

    // -------------------------------------------------------------------------

    private static void assumeFixturePresent() {
        Assumptions.assumeTrue(
                Files.exists(FIXTURE) && Files.isReadable(FIXTURE),
                "Large-file fixture absent — run: source .docker-venv/bin/activate && python simple-datagen.py");
    }
}
